[package]
name = "marco-test-crate"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "simple test crate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
